import type { ReactNode } from "react";
import {
  ArrowRight,
  ArrowUp,
  BarChart3,
  CalendarDays,
  ChevronLeft,
  ChevronRight,
  Download,
  FileBarChart,
  FilePlus2,
  FileText,
  Filter,
  Globe2,
  MoreVertical,
  Search,
  Share2,
  UserRound
} from "lucide-react";
import clsx from "clsx";
import { PageHeader } from "@/components/shared";

const tabs = ["All Reports", "Scheduled", "Generated by Me", "Shared with Me"] as const;

const kpis = [
  {
    title: "Total Reports",
    value: "128",
    detail: "All time",
    icon: FileText,
    tone: "neutral"
  },
  {
    title: "Generated (This Month)",
    value: "24",
    detail: "20% vs last month",
    icon: BarChart3,
    tone: "success",
    trend: true
  },
  {
    title: "Scheduled Reports",
    value: "8",
    detail: "Active schedules",
    icon: CalendarDays,
    tone: "purple"
  },
  {
    title: "Downloads (This Month)",
    value: "56",
    detail: "15% vs last month",
    icon: Download,
    tone: "info",
    trend: true
  }
] as const;

const reports = [
  ["National Risk Assessment - Nov 2024", "Comprehensive risk overview", "Risk", "28 Nov 2024\n10:30 AM", "danger"],
  ["Trade Flow Analysis - Q4 2024", "Import, Export & Transit Data", "Trade", "27 Nov 2024\n04:15 PM", "warning"],
  ["Infrastructure Impact Report", "Damage & Recovery Assessment", "Infrastructure", "26 Nov 2024\n11:50 AM", "info"],
  ["Environmental Impact Summary", "Emissions, Resources & Climate", "Environment", "25 Nov 2024\n09:20 AM", "success"],
  ["AI Parliament - Session Summary", "Key Discussions & Decisions", "Governance", "24 Nov 2024\n02:10 PM", "purple"],
  ["Crisis Response Report - Cyclone", "Odisha Coast | Cyclone Landfall", "Crisis", "23 Nov 2024\n08:45 AM", "danger"],
  ["Economic Impact Snapshot", "Macro-economic Indicators", "Economic", "22 Nov 2024\n06:30 PM", "warning"],
  ["Monthly Impact Dashboard Report", "All Dimensions Overview", "Dashboard", "21 Nov 2024\n10:05 AM", "info"]
] as const;

const metadata = [
  ["Generated On", "28 Nov 2024, 10:30 AM", CalendarDays],
  ["Generated By", "AI Engine", UserRound],
  ["Format", "PDF", FileBarChart],
  ["Size", "6.2 MB", FileText]
] as const;

const viewerTabs = ["Overview", "Key Findings", "Risk Heatmap", "Recommendations", "Details"] as const;

const riskAreas = [
  ["1", "Puri, Odisha (Coastal)", "Critical", "danger"],
  ["2", "Kutch Corridor, Gujarat", "High", "warning"],
  ["3", "Mumbai Port, Maharashtra", "High", "warning"],
  ["4", "Visakhapatnam, Andhra Pradesh", "High", "warning"],
  ["5", "Sundarbans Region, West Bengal", "Medium", "medium"]
] as const;

const quickActions = [
  ["Create New Report", FilePlus2],
  ["Schedule Report", CalendarDays],
  ["Share Report", Share2],
  ["Export Report", FileBarChart]
] as const;

const categories = [
  ["Risk", "32", "danger"],
  ["Infrastructure", "28", "info"],
  ["Trade", "18", "warning"],
  ["Environment", "16", "success"],
  ["Governance", "12", "purple"],
  ["Crisis", "10", "danger"],
  ["Economic", "8", "warning"],
  ["Social", "4", "purple"]
] as const;

const recent = [
  ["National Risk Assessment - Nov 2024", "28 Nov 2024", FileText],
  ["Trade Flow Analysis - Q4 2024", "27 Nov 2024", FileText],
  ["AI Parliament - Session Summary", "24 Nov 2024", Globe2]
] as const;

const panelClass = "surface-card rounded-md p-3.5 text-card-foreground";

export default function ReportsPage() {
  return (
    <div className="space-y-3.5">
      <PageHeader
        title="REPORTS"
        description="Generate, analyze and share intelligence reports"
      />

      <div className="flex flex-wrap items-end justify-between gap-3 border-b border-border/70">
        <div className="flex flex-wrap gap-7">
          {tabs.map((tab, index) => (
            <button
              key={tab}
              className={clsx(
                "h-10 border-b-2 px-1 text-sm font-medium",
                index === 0
                  ? "border-primary text-primary"
                  : "border-transparent text-muted-foreground hover:text-foreground"
              )}
            >
              {tab}
            </button>
          ))}
        </div>
        <div className="mb-2 flex gap-2">
          <button className="btn btn-outline h-9 text-primary">
            <FilePlus2 className="h-4 w-4" />
            Create New Report
          </button>
          <button className="btn btn-outline h-9 text-primary">
            <Download className="h-4 w-4" />
            Export All
          </button>
        </div>
      </div>

      <KpiRow />

      <section className="grid gap-3 xl:grid-cols-[minmax(430px,0.98fr)_minmax(410px,0.9fr)_268px]">
        <ReportLibrary />
        <ReportViewer />
        <aside className="space-y-3.5">
          <QuickActions />
          <ReportCategories />
          <RecentlyAccessed />
        </aside>
      </section>
    </div>
  );
}

function KpiRow() {
  return (
    <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
      {kpis.map((kpi) => {
        const Icon = kpi.icon;
        const hasTrend = "trend" in kpi && kpi.trend;
        const firstDetailToken = kpi.detail.split(" ")[0];

        return (
          <article key={kpi.title} className={clsx(panelClass, "min-h-[96px]")}>
            <div className="flex items-center gap-4">
              <div className={clsx("flex h-14 w-14 shrink-0 items-center justify-center rounded-md border", toneClasses[kpi.tone])}>
                <Icon className="h-7 w-7" />
              </div>
              <div className="min-w-0">
                <p className="truncate text-sm text-foreground">{kpi.title}</p>
                <p className="mt-1 text-3xl font-semibold leading-8 text-foreground">{kpi.value}</p>
                <p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground">
                  {hasTrend ? <ArrowUp className="h-3.5 w-3.5 text-success" /> : null}
                  {hasTrend ? <span className="text-success">{firstDetailToken}</span> : null}
                  {hasTrend ? kpi.detail.replace(firstDetailToken, "") : kpi.detail}
                </p>
              </div>
            </div>
          </article>
        );
      })}
    </section>
  );
}

function ReportLibrary() {
  return (
    <section className={panelClass}>
      <div className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_82px_190px]">
        <label className="flex h-9 items-center gap-2 rounded-md border border-border bg-background/60 px-3 text-muted-foreground">
          <Search className="h-4 w-4" />
          <input
            className="min-w-0 flex-1 bg-transparent text-sm text-foreground outline-none placeholder:text-muted-foreground"
            placeholder="Search reports..."
            aria-label="Search reports"
          />
        </label>
        <button className="btn btn-outline h-9 justify-start px-3 text-xs">
          <Filter className="h-4 w-4" />
          Filters
        </button>
        <button className="btn btn-outline h-9 justify-start px-3 text-xs">
          <CalendarDays className="h-4 w-4" />
          01 Nov 2024 - 28 Nov 2024
        </button>
      </div>

      <div className="mt-5 grid grid-cols-[minmax(220px,1.45fr)_88px_104px_66px] border-b border-border/70 pb-2 text-xs text-muted-foreground">
        <span>Report Name</span>
        <span>Category</span>
        <span>Generated On</span>
        <span>Actions</span>
      </div>

      <div className="divide-y divide-border/60">
        {reports.map(([title, subtitle, category, date, tone], index) => (
          <article
            key={title}
            className={clsx(
              "grid grid-cols-[minmax(220px,1.45fr)_88px_104px_66px] items-center rounded-md px-2 py-2.5 text-xs",
              index === 0 && "border border-primary bg-primary/10"
            )}
          >
            <div className="flex min-w-0 items-center gap-3">
              <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md border border-border bg-secondary/70 text-foreground">
                <FileText className="h-4 w-4" />
              </span>
              <span className="min-w-0">
                <span className="block truncate text-sm font-semibold leading-5 text-foreground">
                  {title}
                </span>
                <span className="block truncate text-xs text-muted-foreground">
                  {subtitle}
                </span>
              </span>
            </div>
            <span>
              <span className={clsx("inline-flex rounded-md border px-2 py-0.5 text-[0.68rem] font-medium", toneClasses[tone])}>
                {category}
              </span>
            </span>
            <span className="whitespace-pre-line text-xs text-foreground">{date}</span>
            <span className="flex items-center gap-3 text-muted-foreground">
              <Download className="h-4 w-4" />
              <MoreVertical className="h-4 w-4" />
            </span>
          </article>
        ))}
      </div>

      <div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-xs text-muted-foreground">
        <span>Showing 1 to 8 of 128 reports</span>
        <div className="flex items-center gap-2">
          <PageButton><ChevronLeft className="h-4 w-4" /></PageButton>
          {["1", "2", "3", "4", "5", "...", "16"].map((page, index) => (
            <PageButton key={`${page}-${index}`} active={index === 0}>{page}</PageButton>
          ))}
          <PageButton><ChevronRight className="h-4 w-4" /></PageButton>
        </div>
      </div>
    </section>
  );
}

function ReportViewer() {
  return (
    <section className={panelClass}>
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <span className="inline-flex rounded-md border border-danger/30 bg-danger/15 px-2 py-0.5 text-xs font-medium text-danger">
            Risk Report
          </span>
          <h2 className="mt-3 truncate text-xl font-semibold leading-7 text-foreground">
            National Risk Assessment - Nov 2024
          </h2>
          <p className="mt-1 text-sm text-muted-foreground">
            Comprehensive risk assessment across all dimensions and regions
          </p>
        </div>
        <div className="flex gap-2">
          <button className="btn btn-outline h-9 text-primary">
            <Download className="h-4 w-4" />
            Download
          </button>
          <button className="btn btn-outline btn-icon h-9 w-9">
            <MoreVertical className="h-4 w-4" />
          </button>
        </div>
      </div>

      <div className="mt-6 grid grid-cols-4 divide-x divide-border/70 border-b border-border/70 pb-4">
        {metadata.map(([label, value, Icon]) => (
          <div key={label} className="flex min-w-0 gap-2 px-3 first:pl-0">
            <Icon className="mt-0.5 h-5 w-5 shrink-0 text-muted-foreground" />
            <div className="min-w-0">
              <p className="text-[0.68rem] text-muted-foreground">{label}</p>
              <p className="truncate text-xs font-medium text-foreground">{value}</p>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-3 flex gap-7 border-b border-border/70">
        {viewerTabs.map((tab, index) => (
          <button
            key={tab}
            className={clsx(
              "h-9 border-b-2 text-xs font-medium",
              index === 0 ? "border-primary text-primary" : "border-transparent text-muted-foreground"
            )}
          >
            {tab}
          </button>
        ))}
      </div>

      <div className="mt-5 grid gap-3 lg:grid-cols-[1.1fr_0.9fr]">
        <ExecutiveSummary />
        <RiskGauge />
      </div>

      <div className="mt-3 grid gap-3 lg:grid-cols-[0.9fr_1.1fr]">
        <RiskByDimension />
        <TopRiskAreas />
      </div>
    </section>
  );
}

function ExecutiveSummary() {
  return (
    <article className="rounded-md border border-border bg-background/45 p-3.5">
      <h3 className="text-sm font-semibold text-foreground">Executive Summary</h3>
      <p className="mt-4 text-xs leading-6 text-muted-foreground">
        This report provides a comprehensive assessment of current risks across economic, infrastructure,
        environmental, social and security dimensions. Overall risk level is <span className="font-semibold text-danger">HIGH</span> with
        critical concerns in coastal regions and trade corridors.
      </p>
    </article>
  );
}

function RiskGauge() {
  return (
    <article className="rounded-md border border-border bg-background/45 p-3.5">
      <p className="text-sm text-muted-foreground">Overall Risk Level</p>
      <p className="mt-5 text-2xl font-semibold text-danger">HIGH</p>
      <p className="mt-2 flex items-center gap-1 text-xs text-muted-foreground">
        <ArrowUp className="h-3.5 w-3.5 text-danger" />
        <span className="text-danger">18%</span> vs last month
      </p>
      <svg className="mt-4 h-20 w-full" viewBox="0 0 190 86" aria-hidden="true">
        <path d="M24 72 A72 72 0 0 1 166 72" fill="none" stroke="hsl(var(--secondary))" strokeWidth="18" strokeLinecap="round" />
        <path d="M24 72 A72 72 0 0 1 142 22" fill="none" stroke="url(#riskGauge)" strokeWidth="18" strokeLinecap="round" />
        <line x1="96" y1="72" x2="148" y2="38" stroke="hsl(var(--border-strong))" strokeWidth="4" strokeLinecap="round" />
        <circle cx="148" cy="38" r="5" fill="hsl(var(--danger))" stroke="hsl(var(--foreground))" strokeWidth="1.5" />
        <defs>
          <linearGradient id="riskGauge" x1="24" x2="150" y1="72" y2="24">
            <stop stopColor="hsl(var(--warning))" />
            <stop offset="0.55" stopColor="hsl(var(--danger))" />
            <stop offset="1" stopColor="hsl(var(--danger))" />
          </linearGradient>
        </defs>
      </svg>
    </article>
  );
}

function RiskByDimension() {
  return (
    <article className="rounded-md border border-border bg-background/45 p-3.5">
      <h3 className="text-sm font-semibold text-foreground">Risk by Dimension</h3>
      <div className="mt-4 grid grid-cols-[108px_1fr] items-center gap-4">
        <div className="relative h-[104px] w-[104px]">
          <div className="absolute inset-0 rounded-full bg-[conic-gradient(hsl(var(--primary))_0_28%,hsl(var(--warning))_28%_50%,hsl(var(--success))_50%_68%,rgb(139_92_246)_68%_86%,hsl(var(--danger))_86%_100%)]" />
          <div className="absolute inset-[26px] rounded-full border border-border bg-card" />
        </div>
        <div className="space-y-2 text-[0.68rem]">
          <Legend label="Infrastructure 28%" color="bg-primary" />
          <Legend label="Economic" color="bg-warning" />
          <Legend label="Environmental 18%" color="bg-success" />
          <Legend label="Social" color="bg-violet-500" />
          <Legend label="Security" color="bg-danger" />
        </div>
      </div>
    </article>
  );
}

function TopRiskAreas() {
  return (
    <article className="rounded-md border border-border bg-background/45 p-3.5">
      <h3 className="text-sm font-semibold text-foreground">Top 5 High Risk Areas</h3>
      <div className="mt-4 space-y-3">
        {riskAreas.map(([rank, area, badge, tone]) => (
          <div key={area} className="grid grid-cols-[24px_1fr_auto] items-center gap-2 text-xs">
            <span className="flex h-5 w-5 items-center justify-center rounded-full bg-secondary text-muted-foreground">
              {rank}
            </span>
            <span className="truncate text-foreground">{area}</span>
            <span className={clsx("rounded-md border px-2 py-0.5 text-[0.65rem] font-semibold", toneClasses[tone])}>
              {badge}
            </span>
          </div>
        ))}
      </div>
    </article>
  );
}

function QuickActions() {
  return (
    <Panel title="QUICK ACTIONS">
      <div className="space-y-1">
        {quickActions.map(([label, Icon]) => (
          <button key={label} className="flex h-11 w-full items-center justify-between gap-3 rounded-md px-2 text-left text-sm text-foreground hover:bg-secondary">
            <span className="flex items-center gap-3">
              <Icon className="h-4 w-4 text-muted-foreground" />
              {label}
            </span>
            <ChevronRight className="h-4 w-4 text-muted-foreground" />
          </button>
        ))}
      </div>
    </Panel>
  );
}

function ReportCategories() {
  return (
    <Panel title="REPORT CATEGORIES">
      <div className="space-y-3">
        {categories.map(([label, count, tone]) => (
          <div key={label} className="flex items-center justify-between gap-3 text-sm">
            <span className={clsx("rounded-md border px-2 py-0.5 text-xs font-medium", toneClasses[tone])}>
              {label}
            </span>
            <span className="text-foreground">{count}</span>
          </div>
        ))}
      </div>
    </Panel>
  );
}

function RecentlyAccessed() {
  return (
    <Panel title="RECENTLY ACCESSED">
      <div className="space-y-3">
        {recent.map(([title, date, Icon]) => (
          <div key={title} className="grid grid-cols-[32px_1fr] gap-3">
            <span className="flex h-8 w-8 items-center justify-center rounded-md border border-border bg-secondary/60 text-muted-foreground">
              <Icon className="h-4 w-4" />
            </span>
            <span className="min-w-0">
              <span className="block truncate text-xs font-semibold text-foreground">{title}</span>
              <span className="block text-xs text-muted-foreground">{date}</span>
            </span>
          </div>
        ))}
      </div>
      <button className="mt-4 flex h-8 w-full items-center justify-center gap-2 rounded-md border border-border bg-background/60 text-xs font-medium text-primary hover:bg-secondary">
        View All Reports
        <ArrowRight className="h-3.5 w-3.5" />
      </button>
    </Panel>
  );
}

function Panel({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className={panelClass}>
      <div className="mb-3 border-b border-border/70 pb-3">
        <h2 className="text-sm font-semibold uppercase leading-5 text-foreground">{title}</h2>
      </div>
      {children}
    </section>
  );
}

function PageButton({ children, active }: { children: ReactNode; active?: boolean }) {
  return (
    <button
      className={clsx(
        "flex h-8 min-w-8 items-center justify-center rounded-md border px-2",
        active
          ? "border-primary bg-primary/15 text-primary"
          : "border-border bg-background/60 text-muted-foreground"
      )}
    >
      {children}
    </button>
  );
}

function Legend({ label, color }: { label: string; color: string }) {
  return (
    <div className="flex items-center gap-2 text-muted-foreground">
      <span className={clsx("h-2.5 w-2.5 rounded-full", color)} />
      <span>{label}</span>
    </div>
  );
}

const toneClasses = {
  danger: "border-danger/30 bg-danger/15 text-danger",
  warning: "border-warning/30 bg-warning/15 text-warning",
  success: "border-success/30 bg-success/15 text-success",
  info: "border-primary/30 bg-primary/15 text-primary",
  purple: "border-violet-500/30 bg-violet-500/15 text-violet-300",
  medium: "border-yellow-400/30 bg-yellow-400/15 text-yellow-300",
  neutral: "border-border bg-secondary/60 text-muted-foreground"
} as const;
